### ISSUE TITLE
Robodyn SAMD21 MINI board

### ISSUE THREAD

**Issue by LordVila** [Kaiwol1990/Mechaduino#4]
Hello Kaiwol1990, first let me thank you for your help to the stepper servo drive world!

I'm currently working on a design based on the Mechaduino but for largers motors, using discrete MOSFETs instead of a dual H-bridge IC drive.

Got a Robodyn SAMD21 MINI board, since use the same microcontroller, and tried to upload your modified code version of Mechaduino but I'm not getting anything on the serial monitor, while the original code from Mechaduino works great. Any idea what could it be?

**Comment by Kaiwol1990** [comment]
Hi LordVila,

sry for not answering. I'm not sure why you aren't getting anything from the SerialPort.
It's basically using the same Port as the original Firmware. Make sure you set the baudrate right and change your Serialparser to send a "\n" after every new line.
