### ISSUE TITLE
0.9 degree stepper not working

### ISSUE THREAD

**Issue by Elvenblood** [Kaiwol1990/Mechaduino#9]
Hi,

I can't get my 0.9 stepper to work with this release. It works somewhat better with the old version.
It runs through the calibration-process, but i get maximal error of around 70%. But I don't get any data for the lookup table and it sort of hangs.

With this version when trying to calibrate I get: "...Motor is not moving -> abbort"
It starts to move but don't really move at all, just oscillates.

Also, mm_rev what should the correct value be?

Thanks for any info

**Comment by Kaiwol1990** [comment]
Hi Elvenblood,

I will take a look at what's going on. There are some bugs in the calibration routine I think.

The mm_rev value is only needed for the maximal error term and for the velocity settings of the downhill simplex algorithm. It's used for a motor with a pulley. If you don't have a pulley that turns the rotation into a linear movement, just set it to 360 and the velocity can be set in deg/s.

**Comment by Kaiwol1990** [comment]
I've uploaded a new Version to the dev branch. Can you please try it for me? 
If it's still not working try the command "calibrate -debug" and upload the output as a file.

**Comment by Elvenblood** [comment]
Thanks for your help. Right now I had to get my 3d printer operational again so I switched back to my old setup. But I will try it as soon as I can. Probably this weekend. I tried it with 1.8 degrees with slightly better results. After a couple of layers it all jumps a few steps in som direction and I need to stop the print. This is the 3rd time I've tried to use the mechaduino and the 3rd set of motors, so I slowly loose hope of ever getting it to work.

I have 20 tooth gt2 pulleys and belts for my core-xy printer running it with 16 microstepping. What should the mm be then?

Thanks again and I'll try to give you the result as soon as I can.

**Comment by Kaiwol1990** [comment]
The mm_rev would be 40 in that case.

The jumps could be a bad lookup table or bad PID settings. Make sure to try the downhill simplex algorithm to tune the motor. You can find it in the autotune tab. 

Did you glue the magnet to the shaft as centered as possible? 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Elvenblood** [comment]
Yes I tried the downhill which tuned it good as far as I could see. But I'll try it again. Yes I've tried glueing and not glueing and tweaking the mechaduino up down left right to no avail. I'll try to make a shim with my 3d printer and see if i can make it even more centered,

Btw nice work with firmware and the GUI for tuning it. Makes the product a lot better.

/E

**Comment by Kaiwol1990** [comment]
Thanks,
I glued the magnets all without a shim, just by hand and it works pretty well for me. 
While tuning with the downhill simplex make sure to set the velocity to your average printing speed.  
And while calibrating it is important that there is no load on the motors ( no belts attached) but I'm sure you know that. Let me know if it works.

- Kai

**Comment by Elvenblood** [comment]
Hello,

The calibration now works. I don't know how accurate it is since the calibration report didn't show the number any more. How can I check the lookup table for errors?

Thanks for the fix. I'll run the downhill autotune later tonight and try som prints and see if it behaves.

/E

**Comment by Kaiwol1990** [comment]
I've uploaded a new version to the dev branch.
if you send a "calibration -check" the mechaduino will step two times through all steps and checks the readings. You then can decide if you want to continue or not. 
You can also send a "-smooth" with it to smooth the calibration table a little bit. This can help with a quieter operation of the mechaduino.

**Comment by Kaiwol1990** [comment]
Hi Elvenblood,

I found another bug in the calibration. The coil current wasn't set right to do the full steps. I also implemented that the motor moves in both directions to compensate that it might want to move more in one direction. 

Could you please check it?

Thanks.
Kai

**Comment by Elvenblood** [comment]
Sorry for the late reply. But sure i'll try it as soon as I have moment over.

/E
